export const GET_ACTOR = "GET_ACTOR"
export const GET_ACTOR_OK = "GET_ACTOR_OK";
export const GET_ACTOR_ERROR = "GET_ACTOR_ERROR";


export const  LOADING_MOVIES = "LOADING_MOVIES";
export const  LOADING_MOVIES_OK = "LOADING_MOVIES_OK";
export const  LOADING_MOVIES_ERROR = "LOADING_MOVIES_ERROR";